# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=30)),
                ('body', models.TextField(default='')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_after_sec', models.IntegerField(blank=True, null=True)),
                ('html_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('avatar_url', models.URLField(null=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr_stats.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr_stats.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='pull_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr_stats.PullRequest'),
        ),
    ]
